# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - run `docker-compose up`

version: "3"

services:
  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:1.0.0-preview
    depends_on:
      - storageadapter
    ports:
      - "9003:9003"
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
    volumes:
      - ./data:/app/data:ro
  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-dotnet:1.0.0-preview
    ports:
      - "9022:9022"
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING